export const ABOUT_EDUCATION = [
  "12. Kongres Delovnih terapevtov Slovenije »Soustvarjanje sprememb od poklica do poslanstva« | [maj 2026]",
  "Udeležba na mednarodni konferenci Ontario Society of Occupational Therapists (OSOT) Conference [23. 10. 2025 – 24. 10. 2025]",
  "Paliativna oskrba otrok | Pediatrična klinika Ljubljana, izvajalke POO PEK [17. 11. – 21. 11. 2025]",
  "Delavnica Mobilizacija živčnega sistema | Gibanje d. o. o., izvajalec: Borut Vrhovnik [15. 11. 2025]",
  "Bobath - RNO osnovni tečaj za delo z otroki in odraslimi | RN Terapija, izvajalka: Neda Rotar [16. 9. 2024 – 7. 2. 2025]",
  "Specifični interesi otrok z avtizmom - Kako jih naslovimo in vključimo v učni proces? | IC Pika, izvajalka: Nastja Oder [28. 5. 2024]",
  "Razvoj in funkcija roke | Sensoland, izvajalki: Lea Šuc in Simona Korelc Primc [22. 9. 2023]",
  "»Ocena grafomotorike pri otroku« z ocenjevalnim instrumentom WRITIC | URI SOČA [24. 10. 2022]",
  "»Vse kar ste hoteli vedeti o motnjah požiranja pa si niste upali vprašati – drugo nadaljevanje« | Slovensko zdravniško združenje za pediatrijo [1. 12. 2022]",
  "Aktivna udeležba na mednarodni konferenci V ritmu človeških možganov | Spominčica [2. 6. 2022]",
  "Aktivna udeležba na prireditvi projekta Celovita obravnava demence v lokalnih okoljih | Dom Upokojencev Franca Salamona [junij 2022]",
  "Seminar Kamišibaj gledališča | Hiša otrok in umetnosti [marec–april 2022]",
  "Anatomija, funkcionalna biomehanika in miofascialne zakonitosti | Peti element studio [maj 2021]",
  "Normalno gibanje | Zbornica Delovnih terapevtov Slovenije, izvajalka: Tinka Rajhner Boštjan [avgust 2020]",
  "Bobath tečaj z nevrološko simptomatiko | Center Fizioterapije Ljubljana [marec 2019 – maj 2019]",
  "Uvod v klinično aromaterapijo | Šola aromaterapije [28. 1. 2018]",
  "Certifikat NEVROMIŠIČNI TAPING v pediatriji in športni travmatologiji | NMT NeuroMuscular Taping Institut, Ljubljana in Koper [5. 6. 2017 – 8. 6. 2017]",
  "Osnovno (paraprofesionalno) izobraževanje v pedagogiki Montessori | Inštitut Montessori, Zavod za pomoč staršem pri razvoju otrok, Sojerjeva ulica 9, 1000 Ljubljana [marec 2016 – april 2016]",
  "Gledališka šola: Trening govornega aparata | JSKD Ljubljana [19. 1. 2015 – 16. 3. 2015]",
  "Pripovedovalska šola | Kulturno društvo Pripovedovalski Variete [31. 1. 2015 – 18. 4. 2015]",
  "Šola sodobnih performativnih in uličnih umetnosti | Društvo Gledališče Ane Monro [marec 2014 – avgust 2014]",
] as const;
